name: Publish latest image at runtime

on:
  push:
    branches:
      - master

env:
  API_URL: 'https://api.github.com/repos/glpi-project/glpi/releases/latest'

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build image
        run: |
          chmod u+x ./setup.sh && ./setup.sh

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image to GHCR
        run: |
          VERSION=bnphu-$(curl -s $API_URL | grep tag_name | cut -d '"' -f 4)
          IMAGE_NAME=glpi:$VERSION
          IMAGE_ID=ghcr.io/${{ github.repository }}

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
